In [30]:
import numpy as np

In [6]:
import torch

In [2]:
import torch.nn as nn # neural network functionalities

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
from torch.utils.data import Dataset

In [17]:
import pandas as pd

In [18]:
data = pd.read_csv(
    "https://raw.githubusercontent.com/fawazsammani/The-Complete-Neural-Networks-Bootcamp-Theory-Applications/master/diabetes.csv"
)

In [19]:
data.columns

Index(['Number of times pregnant', 'Plasma glucose concentration',
       'Diastolic blood pressure', 'Triceps skin fold thickness',
       '2-Hour serum insulin', 'Body mass index', 'Age', 'Class'],
      dtype='object')

In [20]:
x = data.iloc[:,0:-1].values

In [21]:
x

array([[  6. , 148. ,  72. , ...,   0. ,  33.6,  50. ],
       [  1. ,  85. ,  66. , ...,   0. ,  26.6,  31. ],
       [  8. , 183. ,  64. , ...,   0. ,  23.3,  32. ],
       ...,
       [  5. , 121. ,  72. , ..., 112. ,  26.2,  30. ],
       [  1. , 126. ,  60. , ...,   0. ,  30.1,  47. ],
       [  1. ,  93. ,  70. , ...,   0. ,  30.4,  23. ]])

In [22]:
x.shape

(768, 7)

In [23]:
y = list(data.iloc[:, -1])

In [24]:
len(y)

768

In [25]:
y_int = []

In [26]:
for val in y:
    if val == "positive":
        y_int.append(1)
    else:
        y_int.append(0)

In [27]:
y_int

[1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,


In [28]:
# converting to numpy array

In [31]:
y = np.array(y_int, dtype="float64")

In [32]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [18]:
x

array([[  6. , 148. ,  72. , ...,   0. ,  33.6,  50. ],
       [  1. ,  85. ,  66. , ...,   0. ,  26.6,  31. ],
       [  8. , 183. ,  64. , ...,   0. ,  23.3,  32. ],
       ...,
       [  5. , 121. ,  72. , ..., 112. ,  26.2,  30. ],
       [  1. , 126. ,  60. , ...,   0. ,  30.1,  47. ],
       [  1. ,  93. ,  70. , ...,   0. ,  30.4,  23. ]])

In [27]:
# normalizing the values in x matrix between -1 and 1

In [14]:
sc = StandardScaler()

NameError: name 'StandardScaler' is not defined

In [20]:
x = sc.fit_transform(x)

In [21]:
x

array([[ 0.63994726,  0.84832379,  0.14964075, ..., -0.69289057,
         0.20401277,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.69289057,
        -0.68442195, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -0.69289057,
        -1.10325546, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ...,  0.27959377,
        -0.73518964, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.69289057,
        -0.24020459,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.69289057,
        -0.20212881, -0.87137393]])

In [31]:
# convert numpy array to pytorch

In [33]:
x = torch.tensor(x)

In [34]:
y = torch.tensor(y).unsqueeze(1)

In [35]:
x.shape

torch.Size([768, 7])

In [36]:
y.shape

torch.Size([768, 1])

In [37]:
class Dataset(Dataset):
    def __init__(self, x, y):
        self.x  = x
        self.y = y
    def __getitem__(self, index):
        return self.x[index], self.y[index]
    def __len__(self):
        return len(self.x)

In [38]:
dataset = Dataset(x, y)

In [39]:
len(dataset)

768

In [40]:
train_loader = torch.utils.data.DataLoader(dataset = dataset, batch_size= 32, shuffle=True)

In [41]:
train_loader

In [54]:
class Model(nn.Module):
    def __init__(self, input_features, output_features):
        super(Model, self).__init__()
        self.fc1 = nn.Linear(input_features, 5)
        self.fc2 = nn.Linear(5, 4)
        self.fc3 = nn.Linear(4, 3)
        self.fc4 = nn.Linear(3, output_features)
        self.sigmoid = nn.Sigmoid()
        self.tanh = nn.Tanh()

    def forward(self, x):
        out = self.fc1(x)
        out = self.tanh(out)
        out = self.fc2(out)
        out = self.tanh(out)
        out = self.fc3(out)
        out = self.tanh(out)
        out = self.fc4(out)
        out = self.sigmoid(out)

        return out
    
    

In [56]:
net = Model(7, 1)

In [57]:
loss_function = torch.nn.BCELoss(size_average=True)

In [58]:
optimizer = torch.optim.SGD(net.parameters(), lr = 0.1, momentum = 0.9)

In [9]:
# train the network

In [10]:
# parameters

In [60]:
epochs = 200

In [64]:
for epoch in range(epochs):
    for (input, labels) in train_loader:
        input = input.float()
        labels = labels.float()
        # forward the net
        output = net(input)
        loss = loss_function(output, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    # accuracy calculation  => Thresholding 
    output = (output > 0.5).float()
    accuracy = (output == labels).float().mean()
    print("Epoch {}/{}: Loss: {} Accuracy: {:.3f}".format(epoch + 1, 200, loss, accuracy))

Epoch 1/200: Loss: 0.5189406871795654 Accuracy: 0.875
Epoch 2/200: Loss: 0.6051706671714783 Accuracy: 0.719
Epoch 3/200: Loss: 0.6899937391281128 Accuracy: 0.594
Epoch 4/200: Loss: 0.614919900894165 Accuracy: 0.719
Epoch 5/200: Loss: 0.6439284086227417 Accuracy: 0.656
Epoch 6/200: Loss: 0.7298175096511841 Accuracy: 0.531
Epoch 7/200: Loss: 0.6284278035163879 Accuracy: 0.688
Epoch 8/200: Loss: 0.7313620448112488 Accuracy: 0.531
Epoch 9/200: Loss: 0.6631573438644409 Accuracy: 0.625
Epoch 10/200: Loss: 0.6835260391235352 Accuracy: 0.594
Epoch 11/200: Loss: 0.6241298317909241 Accuracy: 0.688
Epoch 12/200: Loss: 0.6264147758483887 Accuracy: 0.688
Epoch 13/200: Loss: 0.6857538223266602 Accuracy: 0.594
Epoch 14/200: Loss: 0.6145382523536682 Accuracy: 0.719
Epoch 15/200: Loss: 0.6110466718673706 Accuracy: 0.719
Epoch 16/200: Loss: 0.7149521112442017 Accuracy: 0.562
Epoch 17/200: Loss: 0.7140923142433167 Accuracy: 0.531
Epoch 18/200: Loss: 0.6251480579376221 Accuracy: 0.688
Epoch 19/200: Loss: 