In [1]:
!nvidia-smi

Thu Oct  5 08:02:26 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:01:00.0 Off |                  N/A |
|  0%   44C    P8              17W / 350W |  20883MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# Pytorch fundamentals 

**Source:** https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
import matplotlib.pyplot as plt

In [6]:
print(torch.__version__)

2.0.1


In [7]:
scalars = torch.tensor(9)

In [8]:
scalars

tensor(9)

In [9]:
# details of a scalar

In [10]:
# dimension

In [11]:
scalars.ndim

0

In [12]:
# get tensor back a python int

In [13]:
scalars.item()

9

In [14]:
# vector

In [15]:
vector = torch.tensor([7, 7])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [18]:
# matrix

In [19]:
matrix = torch.tensor([[7, 9], [8, 10]])

In [20]:
matrix

tensor([[ 7,  9],
        [ 8, 10]])

In [21]:
matrix.ndim

2

In [22]:
matrix.shape

torch.Size([2, 2])

In [23]:
# tensor

In [24]:
t = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [25]:
t.shape

torch.Size([1, 3, 3])

In [26]:
t.ndim

3

#### random tensors
Why random tensors?
They are important because, the way neural networks work is that 
they start with tensors full of random numbers and then adjust those
random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [27]:
torch.rand(3, 4)

tensor([[0.3603, 0.1708, 0.2672, 0.8098],
        [0.0452, 0.2736, 0.6716, 0.0473],
        [0.5590, 0.5838, 0.9152, 0.7243]])

In [28]:
# create a random tensor of size (3, 4)

In [29]:
some_tensor = torch.tensor([1, 2, 4], dtype=torch.float32)

In [30]:
some_tensor.dtype

torch.float32

In [31]:
some_tensor.shape

torch.Size([3])

In [32]:
some_tensor.device

device(type='cpu')

In [33]:
torch.cuda.is_available()

False

In [34]:
# tensor operations

In [35]:
some_tensor = torch.tensor([1, 2, 3])

In [36]:
some_tensor + 10

tensor([11, 12, 13])

In [37]:
some_tensor * 10

tensor([10, 20, 30])

In [38]:
some_tensor - 10

tensor([-9, -8, -7])

In [39]:
# matrix multiplication

In [40]:
# element wise

In [41]:
torch.tensor([1, 2, 3]) * torch.tensor([4, 5, 6])

tensor([ 4, 10, 18])

In [42]:
# dot product

In [43]:
torch.matmul(torch.tensor([1, 2, 3]), torch.tensor([4, 5, 6]))

tensor(32)

In [44]:
# rules for the dotproduct

In [45]:
# 1. inner dimensions must work 

In [46]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.4264, 0.6333],
        [0.8083, 1.2658]])

torch.matmul(torch.rand(2, 3), torch.rand(2, 3)) # this will not work

In [47]:
# 2. the resulting matrix has dim of the outer dim

In [48]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2)) # res -> 2,2

tensor([[0.8985, 1.5653],
        [0.6825, 1.0646]])

In [49]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)) # res -> 3,3

tensor([[0.3713, 0.9912, 0.4499],
        [0.2083, 0.8136, 0.2831],
        [0.3388, 0.7483, 0.3919]])

In [50]:
# we can fix the shape issues with the transpose

In [51]:
t1 = torch.rand(3, 2)

In [52]:
t2 = torch.rand(3, 2)

In [53]:
t1

tensor([[0.8472, 0.2208],
        [0.8562, 0.0942],
        [0.2095, 0.9558]])

In [54]:
t2

tensor([[0.8263, 0.7322],
        [0.3731, 0.6004],
        [0.4350, 0.5555]])

In [55]:
torch.matmul(t1, t2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [56]:
torch.matmul(t1, t2.T)

tensor([[0.8618, 0.4487, 0.4912],
        [0.7764, 0.3759, 0.4247],
        [0.8730, 0.6520, 0.6221]])

In [ ]:
# tensor aggregation

In [57]:
tensor = torch.arange(1, 100, 10)

In [58]:
tensor

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [59]:
tensor.min()

tensor(1)

In [60]:
tensor.max()

tensor(91)

In [61]:
torch.mean(tensor.type(torch.float32))

tensor(46.)

In [ ]:
# sum 

In [62]:
torch.sum(tensor)

tensor(460)

In [ ]:
# positional min and max

In [63]:
tensor.argmin()

tensor(0)

In [64]:
tensor.argmax()

tensor(9)