In [1]:
!nvidia-smi

Wed Oct  4 23:36:42 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:01:00.0 Off |                  N/A |
|  0%   44C    P8              17W / 350W |  20883MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# Pytorch fundamentals 

**Source:** https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
import matplotlib.pyplot as plt

In [6]:
print(torch.__version__)

2.0.1


In [7]:
scalars = torch.tensor(9)

In [8]:
scalars

tensor(9)

In [9]:
# details of a scalar

In [10]:
# dimension

In [11]:
scalars.ndim

0

In [12]:
# get tensor back a python int

In [13]:
scalars.item()

9

In [14]:
# vector

In [15]:
vector = torch.tensor([7, 7])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [18]:
# matrix

In [19]:
matrix = torch.tensor([[7, 9], [8, 10]])

In [20]:
matrix

tensor([[ 7,  9],
        [ 8, 10]])

In [21]:
matrix.ndim

2

In [22]:
matrix.shape

torch.Size([2, 2])

In [23]:
# tensor

In [24]:
t = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [25]:
t.shape

torch.Size([1, 3, 3])

In [26]:
t.ndim

3

In [27]:
## random tensors

In [28]:
torch.rand(3, 4)

tensor([[0.2776, 0.7345, 0.6426, 0.6741],
        [0.6767, 0.0910, 0.4502, 0.9631],
        [0.4463, 0.5526, 0.9087, 0.1268]])

In [29]:
torch.zeros(size=(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
# ranges

In [33]:
torch.arange(1, 12)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
torch.arange(start=1, end=10, step=1)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
torch.zeros_like(torch.arange(start=1, end=10, step=1))

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
### tensor datatypes

In [37]:
t = torch.tensor([1, 3, 5])

tensor([1, 3, 5])

In [38]:
t.dtype

torch.int64

In [39]:
## Three errors you will meet with tensors

1. Tensors not right datatype

2. Tensors not right shape

3. Tensors not on right device

In [42]:
ex = torch.tensor([3.0, 6.0, 9.0], dtype=None, device="cpu", requires_grad=True)

dtype -> what datatype
device -> cpu cuda or else
requires_grad -> should we track of the gradients
