In [1]:
import torch

In [2]:
x = torch.arange(1, 10).reshape(1, 3, 3)

In [3]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
x[0, 0]

tensor([1, 2, 3])

In [6]:
x[0][0]

tensor([1, 2, 3])

In [7]:
x[0, 0, 0]

tensor(1)

In [8]:
x[0][0][0]

tensor(1)

In [9]:
# select all the target dimensions with :

In [10]:
x[:, 0]

tensor([[1, 2, 3]])

In [11]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [12]:
x[:, 1, 1]

tensor([5])

In [13]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
x[:, :, 2], x[:, :, 2].squeeze()

(tensor([[3, 6, 9]]), tensor([3, 6, 9]))

In [15]:
# numpy and tensors

In [16]:
import numpy as np

In [17]:
array = np.arange(1, 8)

In [18]:
tensor = torch.from_numpy(array)

In [19]:
array.dtype

dtype('int64')

In [20]:
tensor.dtype

torch.int64

In [21]:
tensor.type(torch.int32)

tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32)

In [22]:
tensor.dtype

torch.int64

In [23]:
# torch to numpy

In [24]:
torch.arange(1, 10), torch.arange(1, 10).numpy()

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [25]:
torch.cuda.is_available()

True

In [26]:
!nvidia-smi

Thu Oct  5 23:40:57 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:01:00.0 Off |                  N/A |
|  0%   44C    P8              18W / 350W |      5MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [27]:
torch.zeros(1).cuda()

tensor([0.], device='cuda:0')