In [1]:
import torch

In [2]:
tensor = torch.arange(1, 10)

In [3]:
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
tensor = tensor.reshape(1, 9)

In [6]:
tensor.shape

torch.Size([1, 9])

In [7]:
tensor.squeeze(), tensor.squeeze().shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [9]:
tensor

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
tensor = tensor.reshape(9)

In [11]:
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
tensor.unsqueeze(dim=0), tensor.unsqueeze(dim=0).shape, tensor.unsqueeze(dim=1), tensor.unsqueeze(dim=1).shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([1, 9]),
 tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [13]:
# permute 

In [14]:
x_original = torch.rand(size=(224, 224, 3))

In [18]:
x_original.shape

torch.Size([224, 224, 3])

In [17]:
torch.permute(x_original, (2, 1, 0)).shape

torch.Size([3, 224, 224])