### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep
the same memory as original tensor
* Stacking - combine multiple tensors on top of each other or side by side
* squeezing - removes all 1 dim from a tensor
* unsqueezing - add a 1 dim to a target tensor

In [2]:
import torch

In [4]:
tensor = torch.arange(1, 10)

In [8]:
tensor.shape

torch.Size([9])

In [11]:
tensor.reshape(1, 9).shape

torch.Size([1, 9])

In [12]:
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
tensor.shape

torch.Size([9])

In [14]:
tensor.reshape(9, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [15]:
tensor.view(9, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [16]:
z = tensor.view(9, 1)

In [17]:
z

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [18]:
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
z[:, 0] = 2

In [20]:
z[:, 0]

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
z

tensor([[2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2],
        [2]])

In [22]:
tensor

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
z, z.shape

(tensor([[2],
         [2],
         [2],
         [2],
         [2],
         [2],
         [2],
         [2],
         [2]]),
 torch.Size([9, 1]))

In [24]:
# stacking

In [25]:
x_stacked = torch.stack([tensor, tensor, tensor], dim=0)

In [26]:
x_stacked

tensor([[2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [27]:
x_stacked = torch.stack([tensor, tensor, tensor], dim=1)

In [28]:
x_stacked

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

**Squeezing and unsqueezing**

In [39]:
tensor, tensor.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [44]:
tensor.unsqueeze(dim=0), tensor.unsqueeze(dim=0).shape, tensor.unsqueeze(dim=1), tensor.unsqueeze(dim=1).shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 torch.Size([1, 9]),
 tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))